name: topitup
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rename: ^2.0.1
  flutter_screenutil: ^5.5.3+2
  introduction_screen: ^3.0.2
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.1.0
  form_field_validator: ^1.1.0
  flutter_svg: ^1.1.4
  http: ^0.13.5
  provider: ^6.0.3
  platform_device_id: ^1.0.1
  loading_overlay: ^0.3.0
  flutter_secure_storage: ^6.0.0
  intl_phone_number_input: ^0.7.0+2
  libphonenumber: ^2.0.2
  flutter_native_contact_picker: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/splash/
    - assets/onboarding/
    - assets/svg/
    - assets/logos/

  fonts:
    - family: SF-Pro-Text
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
